### ISSUE TITLE
Fails if GOPATH is not set

### ISSUE THREAD

**Issue by xrl** [lsegal/yard-go#5]
I was trying to generate the yardocs for `aws-sdk-go` for offline mode and I was getting exceptions when generating the HTML files. Turns out https://github.com/lsegal/yard-go/blob/master/lib/yard-go/extensions.rb#L5 was trying to concatenate a nil with a string. Simply setting the `GOPATH` solved the issue but a prescriptive message would have been nicer.

**Comment by lsegal** [comment]
Thanks for reporting!
